### ISSUE TITLE
docs: Can I show or hide text based on whether a list item has been selected

### ISSUE THREAD

**Issue by atreeon** [felangel/mason#1104]
**Description**
I have a list of values as a variable / parameter
```
  platforms:
    type: array
    values:
      - macos
      - web
      - android
    default: 
      - macos
    prompt: platforms
```

Can I check whether that the item has been selected or not?
```
{{#if platforms contains 'macos'}}
  # Code that should only be executed on macOS
{{/if}}
```
