### ISSUE TITLE
fix: mason don't validate brick path on the get command

### ISSUE THREAD

**Issue by erickzanardo** [felangel/mason#111]
**Description**

When having bricks with non-existent paths in the `mason.yml` file, the `mason get` commands work fine, but then when using `mason make brick`, it gives a `Could not find brick at PATH`

**Steps To Reproduce**

Have the following `mason.yml`
```
bricks:
  flame_package:
    git:
      url: git@github.com:flame-engine/flame-bricks.git
      path: some_folder
```

Run `mason get`
Run `mason make flame_package`

You should see a `Could not find brick at` error

**Expected Behavior**
The error should be reported on the `mason get` command, and not on the `make` one
