### ISSUE TITLE
fix: Extra line with condition statement

### ISSUE THREAD

**Issue by Pierre-Monier** [felangel/mason#1253]
**Description**
According to the documentation, this : 

```
{{^publish}}
publish_to: none
{{/publish}}
dependencies:
  flutter:
    sdk: flutter
  {{#useGoogleFonts}}
  google_fonts: latest
  {{/useGoogleFonts}}
```

with the following configuration : 

```
{
  "publish": false,
  "useGoogleFonts": true
}
```

should generate this : 

```
publish_to: none
dependencies:
  flutter:
    sdk: flutter
  google_fonts: latest
```

But in reality, what it generates is the following : 

```

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  
  google_fonts: latest

```

As you can see, there is some extra space.

**Steps To Reproduce**

1. Clone [this repository](https://github.com/Pierre-Monier/demo_bug_mason) 
2. at the root, run `mason get && mason make demo -c config.json -o ./output`
3. See the generated file in `./output/HELLO.md`

**Expected Behavior**

The generated file should have no extra space, as described in the doc

**Comment by alestiago** [comment]
Hi @Pierre-Monier !

You an already solve this by not including the new line:

```yaml
{{^publish}}publish_to: none{{/publish}}

dependencies:
  flutter:
    sdk: flutter{{#useGoogleFonts}}
  google_fonts: latest{{/useGoogleFonts}}

```

Alternatively, you can use Mustache comments to avoid the line break:

```yaml
{{^publish}} publish_to: none {{/publish}}

dependencies:
  flutter:
    sdk: flutter
  {{#useGoogleFonts}}{{!
}}  google_fonts: latest{{!
}} {{/useGoogleFonts}}
  ```
  
In my honest opinion, I think both solutions hinder readability and I would like an option that doesn't hinder the readability as much. Although, a solution that does so may start to deviate from the Mustache specification.
