### ISSUE TITLE
Support Multiple Templates in One Build Command

### ISSUE THREAD

**Issue by mtwichel** [felangel/mason#13]
# Motivation
I'm about to implement some templates into my Flutter app, but I ran into one little snag.

It would be super nice if you could specify multiple template files to build when writing your `mason.yaml`. For example, running `mason build widget` could generate view code and a test file.

We also may want to move where the `vars` property lives. I believe they are still bound to each template? If they were bound to a build command it would be easy to share them with multiple template files. Since `mason.yaml` is now required I don't think that's much of a stretch anyway. 

If we're doing that, does it make sense to move all that metadata into a build command? I know we don't want to over-engineer the tool, but maybe it makes sense to keep the `mason.yaml` option available, but still pass in simple `template.yaml` files as well?

# Example
`mason.yaml`
```yaml
builds:
  greetings:
    description: A simple greeting in markdown.
    templates:
      - path: ./greetings.md
    vars:
      - name
  widget:
    description: A Flutter widget containing a view, bloc, and test scafold for the bloc.
    templates:
      - git:
          url: git@github.com:felangel/mason.git
          path: templates/widget/view_template.dart.txt
      - git:
          url: git@github.com:felangel/mason.git
          path: templates/widget/test_template.dart.txt
    vars:
      - name
      - generateBloc
```

YMK what you think. I'm happy to jump on a call to discuss, and happy to contribute the feature in a PR if you think it's a good direction to take things 🙂
