### ISSUE TITLE
I cannot publish my mason brick

### ISSUE THREAD

**Issue by saddemYassin** [felangel/mason#1372]
**Description**

I tried to publish my brick on brickHub after login, but an error occurred. 

**Steps To Reproduce**

1. I just run `mason publish --directory ./` 

**Expected Behavior**

Publish successfully.

**Actual result**

```zsh
yassinsaddem@yassins-MBP custom_stacked_project_starter % mason publish --directory ./
✓ Bundled custom_stacked_project_starter (0.5s)

Publishing is forever; bricks cannot be unpublished.
See policy details at https://brickhub.dev/policy

Do you want to publish custom_stacked_project_starter 0.1.0+1? (y/N) Yes
✗ Publishing custom_stacked_project_starter 0.1.0+1 (0.6s)
Malformed bundle.
The brick.yaml repository field must be provided.
yassinsaddem@yassins-MBP custom_stacked_project_starter % ls                          
CHANGELOG.md                            README.md                               brick.yaml                              hooks
LICENSE                                 __brick__                               custom_stacked_project_starter.bundle
```

**Additional Context**

And this my `brick.yaml` file
```yaml
name: custom_stacked_project_starter
description: A mason brick created with the Mason CLI to generate a custom stacked starter project.

version: 0.1.0+1

environment:
  mason: ">=0.1.0-dev.57 <0.1.0"

vars:
  uses_test:
    type: boolean
    description: A flag to indicate if the project uses unit test and widget test
    default: true
    prompt: Do you use unit test and widget test?
```
