### ISSUE TITLE
feat: Allow executing jobs via `mason do`

### ISSUE THREAD

**Issue by jtdLab** [felangel/mason#1386]
@felangel 

**Description**

Currently `mason` allows defining bricks + some hooks pre and post generation this helps a lot with work that requires some files to be generated.

But often when building dart projects there are also certain tasks that do NOT involve that generation step.

Therefore jobs are introduced.

A project could look like this:

```
bricks/
     ...
jobs/
     job_a
          run.dart
          job.yaml
          pubspec.yaml
     job_b
          run.dart
          job.yaml
          pubspec.yaml
     ...
```

`job.yaml`
```yaml
name: job_a
description: The job A.
version: 1.0.0

environment:
  mason: ">=0.1.0-dev.57 <0.1.0"

args:
  fail-fast:
    type: bool
    description: Fail after first error.
    default: false
```

`run.dart`
```dart
import 'package:mason/mason.dart';

Future<void> run(JobContext context) async {
 // JobContext allows accessing the job args defined in job.yaml
 final failFast =  context.args['failFast'];

 // Do some stuff
}

```

Jobs can then be added to `mason.yaml` resulting in:

`mason.yaml`
```yaml
bricks:
     ...
jobs:
     job_a
          path: jobs/job_a
     job_b
          path: jobs/job_b
     ...
```

And are finally available via:

```sh
mason do job_a --fail-fast
```
