### ISSUE TITLE
How to keep {{var.var2}}?

### ISSUE THREAD

**Issue by huang12zheng** [felangel/mason#160]
**Description**
file in brick:
```yaml
...
with:
     credential: ${{ secrets.CREDENTIAL_JSON }}
...
```
it would switch to as follow
```
...
with:
     credential: $
...
```
I don't want to change ${{ secrets.CREDENTIAL_JSON }}

>  I also tried {{{ }}}. it is the same thing

* **reproduct**
1. mason new hello
~2. remove vars in brick.yaml~
2. make vars something like var1.var2
3. change content of HELLO.md

~name: hello~
~description: A new brick created with the Mason CLI.~
~vars:~

* Fri Dec  3 13:24:18 CST 2021
- [ ] Question: Whether vars,which is with split by ., are allowed in brick.yaml?
Example:
```yaml
name: hello
description: An example hello brick.
vars:
  - "name.a"
```
> This might prompt an error: use var: name for the prompt
