### ISSUE TITLE
feat: Add optional default values to brick template

### ISSUE THREAD

**Issue by Luckey-Elijah** [felangel/mason#169]
**Description**

Currently when working with a brick template when create the metadata like this:

```yaml
name: example
description: An example brick
vars:
  - name
```

Perhaps we could have an option to provide a default value in the brick:

```yaml
name: example
description: An example brick
vars:
  - name: Elijah Luckey # will now generate with this default value
```

I can think of two options for how the CLI could handle it:
- User **is not prompted** for the value and will always accept the default value (probably undesirable)
- User **is prompted** for the value and can just press Enter to accept the default

No prompt

```sh
mason make hello
✓ Used default value: name: Elijah Luckey (0.0s)
✓ Made brick hello (0.0s)
✓ Generated 1 file:
  ~/my-project/HELLO.md (new)
```

With prompt, provided alternative to the default

```sh
mason make hello
name (Elijah Luckey): Felix
✓ Made brick hello (0.0s)
✓ Generated 1 file:
  ~/my-project/HELLO.md (new)
```

With prompt, accepting the default

```sh
mason make hello
name (Elijah Luckey):
✓ Used default value: name: Elijah Luckey (0.0s)
✓ Made brick hello (0.0s)
✓ Generated 1 file:
  ~/my-project/HELLO.md (new)
```

**Requirements**

- [ ] A brick can accept an optional value in the declaration of the variable
- [ ] When a default value is set, user **will not** be prompted for the `var`
or
- [ ] When a default value is set, user **will** be prompted for the `var` and can accept the default value in the prompt

**Additional Context**

n/a
