### ISSUE TITLE
fix: Hooks - Could not find a command named  "{"name":"aaon"}".

### ISSUE THREAD

**Issue by aaongr** [felangel/mason#314]
Hello,
What a Wonderful World is the One that we live in :)

In my mason project (https://github.com/itgaia/itg_mason), I want to use the hooks functionality
I created a new brick template for testing the hooks, `test_template`

    mason new test_template -o ./bricks

mason.yaml
```yaml
bricks:
  test_template:
    path: ./bricks/test_template
```

bricks/test_template/brick.yaml
```yaml
name: test_template
description: A new brick created with the Mason CLI.
version: 0.1.0+1
environment:
  mason: ">=0.1.0-dev <0.1.0"
vars:
  name:
    type: string
    description: The name of the app (pascalCase)
    prompt: What is the app name?
```

    mason get
    mason list
    mason make test_template --name TestApp -o ./generated/test_app

    mkdir -p bricks/test_template/hooks
    touch bricks/test_template/hooks/pre_gen.dart
    touch bricks/test_template/hooks/pubspec.yaml

bricks/test_template/hooks/pubspec.yaml
```yaml
name: test_template_hooks

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  mason: any
```

bricks/test_template/hooks/pre_gen.dart
```dart
import 'package:mason/mason.dart';

void run(HookContext context) {
  context.logger.info('hello {{name}}!');
}
```

When I run make it failed:
```
itg_mason (main) $     mason make test_template --name TestApp -o ./generated/test_app
Could not find a command named "{"name":"TestApp"}".

```

Any ideas?

My current mason ver is: 0.1.0-dev.17

With my warmest regards for all the World

aAon

**Comment by felangel** [comment]
Hi @aaongr 👋 
Thanks for opening an issue!

Did you run `mason add` to install the brick? Are you able to share a screen recording that illustrates the steps you're taking? Thanks!

**Comment by aaongr** [comment]
Dear @felangel,
A wonderful and amazing day for all of Us :)

No I did not run `mason add` (should I have run it?)
I am not sure how should I use the `mason add`, it is not very clear to me...
Can you give me an example?

If `mason add` adds the brick to the mason.yaml, I done it by my self, editing the `mason.yaml`
```yaml
  test_template:
    path: ./bricks/test_template
```
Then I edited the `brick.yaml'
```yaml
ame: test_template
description: A new brick created with the Mason CLI.
version: 0.1.0+1
environment:
  mason: ">=0.1.0-dev <0.1.0"
vars:
  name:
    type: string
    description: The name of the app (pascalCase)
    prompt: What is the app name?
```
Then I run:
```
mason get
mason list
mason make test_template --name TestApp -o ./generated/test_app
```
and the `make` command completed successfully...

Then I created the folder and the files:
```
mkdir -p bricks/test_template/hooks
touch bricks/test_template/hooks/pre_gen.dart
touch bricks/test_template/hooks/pubspec.yaml
```
bricks/test_template/hooks/pubspec.yaml
```yaml
name: test_template_hooks

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  mason: any
```

bricks/test_template/hooks/pre_gen.dart
```dart
import 'package:mason/mason.dart';

void run(HookContext context) {
  context.logger.info('hello {{name}}!');
}
```
When I run `make` again, this time it failed:
```
itg_mason (main) $     mason make test_template --name TestApp -o ./generated/test_app
Could not find a command named "{"name":"TestApp"}".
```
I do not know if it is relevant but in my mac the `mason update` fails.
It makes the update and it reports success, but when I run `mason --version` it shows the previous version, not the new one....

**Comment by michalgauza** [comment]
@aaongr have you find solution for this? :)

**Comment by aaongr** [comment]
> @aaongr have you find solution for this? :)

Dear @michalgauza ,
unfortunately I did not find yet the time to work with it...
So no...
I am sorry...

**Comment by michalgauza** [comment]
@aaongr ok, thanks for response :)

**Comment by michalgauza** [comment]
Hi m@felangel, maybe you have idea what i'm doing wrong?
My path: 
1. create brick with mason new test
2. add brick with `mason add test --path test`
3. add hooks files (copy from https://github.com/felangel/mason/blob/master/bricks/hooks/hooks/pubspec.yaml and change in pubspec.yml `hooks_hooks` => `test_hooks`)

files: 
pubspec.yaml:
```
name: test_hooks

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  mason:
    git:
      url: https://github.com/felangel/mason
      path: packages/mason
```

HELLO.md
`Hello {{name}}!`

post_gen.dart
```
import 'dart:io';
import 'package:mason/mason.dart';

void run(HookContext context) {
  final file = File('.post_gen.txt');
  file.writeAsStringSync('post_gen: {{name}}');
}
```

pre_gen.dart

```
import 'dart:io';
import 'package:mason/mason.dart';

void run(HookContext context) {
  final file = File('.pre_gen.txt');
  file.writeAsStringSync('pre_gen: {{name}}');
}
```
