### ISSUE TITLE
feat: support for enum variables in a brick

### ISSUE THREAD

**Issue by wolfenrain** [felangel/mason#324]
**Description**

As a user, I would like to be able to have variables that can only be one of a list (like an enum).

Currently a user have a variable of type string and then have a hook that validate if the variable value is contained in a list. This requires users to write hooks (in Dart) which is not user-friendly for a semi-simple feature.

A proposal of enum support could be:
```yaml
vars:
  my-enum:
    type: enum
    values:
    - one
    - two
    - three
    default: one # has to match the values
```

Enum variables will still be of a type string I suspect, as the runtime code won't be able to create proper typings for it in hooks.

**Requirements**

- [ ] Being able to add a enum type variable
- [ ] Adding different enum values to a list
- [ ] Default should still work, but has to match a value in the list
