### ISSUE TITLE
fix: StdinException when using enums on Windows (10/11)

### ISSUE THREAD

**Issue by LukeMoody01** [felangel/mason#397]
**Description**

Using enums in your brick.yaml will cause a StdinException when executing `mason make <brick>`

**Steps To Reproduce**

1. Create a new brick
2. Have an enum variable:
```
  color:
    type: enum
    default: red
    description: The color of the sky
    prompt: What is the color of the sky?
    values:
      - red
      - yellow
      - blue
```
4. Run the `mason make <brick>`  *On Windows (10/11)
5. See error

**Expected Behavior**

The developer should be able to use enum values on Window devices 

**Screenshots**
When you get to the enum variable
![image](https://user-images.githubusercontent.com/73887660/172610337-5fc22417-1509-4e37-8f95-c7b85a7e4b06.png)

**Additional Context**

Edit: Checked on Mac, and everything is working as expected. This issue seems to only be on Windows (10/11)
