### ISSUE TITLE
fix: FileSystemException: Directory listing failed (activate brick with git on Windows)

### ISSUE THREAD

**Issue by DeMarcoMan** [felangel/mason#496]
Hello Felix,

We are using your tool for creating new pages/controllers in our apps and it helps us a lot, but we have an issue on Windows.
On macOS we don't have this problem.

**Description**

We get this exception on WIndows:
```
FileSystemException: Directory listing failed, path = 'C:/Users/mwildenb/AppData/Local/Mason/Cache/git/rubigo_page_Z2l0QGJpdGJ1Y2tldC5vcmc6ZGFsb3N5L3J1Ymlnb19wYWdlLmdpdA==_e85b222e08c551eec5689f9629e45501bf0
52670\__brick__\lib\pages\{{#snakeCase}}{{page_id}}_{{page_name}}{{\snakeCase}}\{{#snakeCase}}{{page_id}}_{{page_name}}{{\*' (OS Error: The system cannot find the path specified.
, errno = 3)

```

**Steps To Reproduce**
1. mason get
2. mason make rubigo_page
3. See error

**Mason.yaml**
This is the mason.yaml:
```
bricks:
  rubigo_page:
    git:
      url: "git@bitbucket.org:dalosy/rubigo_page.git"
      path: 
      ref: V1.0.0
```

**Additional Context**
We use the latest mason version: 0.1.0-dev.34

**Related issues**
#56 
#75
