### ISSUE TITLE
nested File paths don't work 

### ISSUE THREAD

**Issue by mrgnhnt96** [felangel/mason#50]
**Description**

the slash `/` is replaced with `&#x2F;` in nested folders

Within my brick template I have 
__brick__
   - {{url}}
        - {{#snakeCase}}{{name}}{{/snakeCase}}.dart

my brick.yaml
```yaml
name: widget
description: A custom Flutter widget
vars:
  - name
  - routable
  - url
``` 

When I make the brick it creates the file in this folder
```
mason make widget
name: dart container
routable: false
url: features/dart_container
✓ Made brick widget (24.8ms)
✓ Generated 1 file(s):
  .../features&#x2F;dart_container/dart_container.dart (new)
```

instead of `features&#x2F;dart_container` it should be `features/dart_container`

**Steps To Reproduce**

1. add a folder with the name of {{url}}
2. provide features/dart_container for the url tag

**Expected Behavior**
instead of `features&#x2F;dart_container` it should be `features/dart_container`
