### ISSUE TITLE
fix: default values for array are not selected

### ISSUE THREAD

**Issue by LukeMoody01** [felangel/mason#530]
**Description**

When using default values in an array variable, if the user presses `enter` for default, an empty array is given instead.

**Steps To Reproduce**

1. Create a new brick
2. In brick.yaml, add the following variable:
```
vars:
  arrayTest:
    type: array
    default: [one, two, three]
    description: This is an arrayTest desc
    prompt: What numbers do you want?
    values:
      - one
      - two
      - three
```
3. Run the brick and use the default values for arrayTest
4. Verify default values used

**Expected Behavior**

As a user, I expect the specified default array to be used

**Additional Context**

Not sure if I may be specifying the default wrong?

Mason Ver: 0.1.0-dev.35
System: Windows 11
