### ISSUE TITLE
fix: Declare brick.yaml variable as a list of strings

### ISSUE THREAD

**Issue by matthew-carroll** [felangel/mason#583]
**Description**

I'd like to configure one of my brick variables to be a list of strings. I'd like to provide a default value for that list in brick.yaml.

```yaml
vars:
  some_list_var:
    type: array
    description: Some description
    default: 
      - This is the default option
    prompt: What items do you want?
```

**Expected Behavior**

I'm prompted for a list of values, with the default set to what configuration in the brick.yaml file.

**Actual behavior**

I get an error when running mason.

**Screenshots**

![Screen Shot 2022-10-28 at 10 15 31 PM](https://user-images.githubusercontent.com/7259036/198815205-f517b115-68d8-4cfa-83a4-a933bd6b87ee.png)
In this case, the variable is named "copyright_holders"

**Comment by felangel** [comment]
Hi @matthew-carroll 👋 
Thanks for opening an issue!

The `array` type expects you to provide a list of values from which the user can choose zero or more values:

```yaml
vars:
  flavors:
    type: array
    description: The supported flavors.
    prompt: Please select the flavors
    values:
      - development
      - integration
      - production
```

```sh
? Please select the flavors
❯ ◯  development
  ◯  integration
  ◯  production
```

If you want a users to enter a free-form list then you can just use type `string` and prompt them to provide a list:

```yaml
vars:
  flavors:
    type: string
    description: The supported flavors.
    prompt: What flavors do you want?
    default: '["development", "production"]'
```

Or you can also use type `string` and prompt them to enter a comma-separated list (for example) and you can parse the input and convert it to a list in a `pre_gen.dart` hook:

```yaml
vars:
  flavors:
    type: string
    description: The supported flavors.
    prompt: What flavors do you want? (as a comma separated list)
    default: "development,production"
```

```dart
// pre_gen.dart
import 'package:mason/mason.dart';

void run(HookContext context) {
  // Manipulate the user's string input and convert it to a list
  context.vars['flavors'] = context.vars['flavors'].split(',');
}
```

Let me know if that helps!

**Comment by matthew-carroll** [comment]
In my case I'm interested in a list of free-form values.

Given that lists are supported for bounded sets, is there any reason not to support lists of free-form values? I would assume that such situations aren't uncommon, and registering programmatic hooks to support comma-separated lists of free-form values seems like a considerable amount of work, when multiplied across all the Mason users.

In fact, is there any particular philosophy about which filters, transforms, etc are included with Mason? I know there are a bunch of case-formatting lambdas, but I think those were all that were listed in the README.

**Comment by felangel** [comment]
> In my case I'm interested in a list of free-form values.
>
> Given that lists are supported for bounded sets, is there any reason not to support lists of free-form values? I would assume that such situations aren't uncommon, and registering programmatic hooks to support comma-separated lists of free-form values seems like a considerable amount of work, when multiplied across all the Mason users.

This is already possible without hooks if you're okay with users providing the input as a list:

```yaml
vars:
  flavors:
    type: string
    description: The supported flavors.
    prompt: What flavors do you want?
    default: '["development", "production"]'
```

It all just comes down to what you want the user experience to be. What would be your ideal API resulting user experience? I'm more than happy to extend the existing API (maybe with a `list` type) but we just need to define what the API and resulting prompting experience would be.

> In fact, is there any particular philosophy about which filters, transforms, etc are included with Mason? I know there are a bunch of case-formatting lambdas, but I think those were all that were listed in the README.

The philosophy has been to include lambdas for common transforms and leave it up to developers to handle one-off/less common use cases via hooks. You can find a complete list of supported lambdas in the [docs](https://docs.brickhub.dev/brick-syntax#built-in-lambdas).
