### ISSUE TITLE
fix(vscode): ssh pattern is not recognized in mason schema

### ISSUE THREAD

**Issue by hugo-pcl** [felangel/mason#652]
**Description**

When adding a brick in the `mason.yaml` file with the vscode extension. It is not possible to add a url with the ssh scheme without error.

**Steps To Reproduce**

1. Go to your `mason.yaml`
2. Add a brick with ssh scheme:
```yaml
bricks:
  my_brick:
    git:
      url: ssh://user@server.fr/awesome_bricks.git
      path: bricks/my_brick
```
3. See error `String does not match the pattern of "^https?://".`

**Expected Behavior**

We should be able to use the ssh scheme like in the `pubspec.yaml` file.

<img width="819" alt="Capture d’écran 2022-12-07 à 21 31 48" src="https://user-images.githubusercontent.com/25439050/206341963-08c8aa03-2b17-4908-a290-55c371b1734a.png">
