### ISSUE TITLE
fix: bug when using a brick from github

### ISSUE THREAD

**Issue by KamiTzayig** [felangel/mason#726]
**Description**

taking a working brick from github fails

**Steps To Reproduce**

1. Go to the repository of the feature_brick: https://github.com/LukeMoody01/mason_bricks/tree/master/bricks/feature_brick
2. add it to the mason.yaml
3. run mason get feature_brick
5. See errors

**Expected Behavior**

i wanted it to work as if i got it from brickhub.dev with "mason add feature_brick"
**Screenshots**

<img width="913" alt="Screenshot_20230202_103253" src="https://user-images.githubusercontent.com/72403698/216272762-fad68198-90d6-4a38-85bf-be01af5d740d.png">

**Comment by felangel** [comment]
Hi @KamiTzayig 👋
Thanks for opening an issue!

I’ll take a closer look asap! Seems to be a windows specific issue potentially similar to #496

**Comment by AngeloAvv** [comment]
Hey @felangel , I'm facing random errors like

`PathNotFoundException: Cannot open file, path = '/Users/angeloavv/.mason-cache/git/pine_bricks_aHR0cHM6Ly9naXRodWIuY29tL015TGl0dGxlU3VpdGUvcGluZV9icmlja3MuZ2l0_86ab178b47759e3f88eeff4a82edf6d2719096e2/pine_retrofit/brick.yaml' (OS Error: No such file or directory, errno = 2)
`

both on macOS Ventura (arm64) and Linux (Debian 11 x64)

It's weird because the files are there, and if you randomly keep running 'mason get', the error moves from one brick to another. As a result, you'll see the .lock file change its references on every execution.

**Comment by felangel** [comment]
> Hey @felangel , I'm facing random errors like
> 
> `PathNotFoundException: Cannot open file, path = '/Users/angeloavv/.mason-cache/git/pine_bricks_aHR0cHM6Ly9naXRodWIuY29tL015TGl0dGxlU3VpdGUvcGluZV9icmlja3MuZ2l0_86ab178b47759e3f88eeff4a82edf6d2719096e2/pine_retrofit/brick.yaml' (OS Error: No such file or directory, errno = 2) `
> 
> both on macOS Ventura (arm64) and Linux (Debian 11 x64)
> 
> It's weird because the files are there, and if you randomly keep running 'mason get', the error moves from one brick to another. As a result, you'll see the .lock file change its references on every execution.
> 
> I think it might be related to filesystem filename max number of characters: https://en.wikipedia.org/wiki/Apple_File_System

Can you share a link to a minimal reproduction sample?

**Comment by AngeloAvv** [comment]
Sure! Simply init your project by running `mason init` and then past all these bricks in the mason.yaml

``` yaml
bricks:
  pine:
    git:
      url: https://github.com/MyLittleSuite/pine_bricks.git
      path: pine
  pine_bloc:
    git:
      url: https://github.com/MyLittleSuite/pine_bricks.git
      path: pine_bloc
  pine_cubit:
    git:
      url: https://github.com/MyLittleSuite/pine_bricks.git
      path: pine_cubit
  pine_dto_mapper:
    git:
      url: https://github.com/MyLittleSuite/pine_bricks.git
      path: pine_dto_mapper
  pine_model:
    git:
      url: https://github.com/MyLittleSuite/pine_bricks.git
      path: pine_model
  pine_network_jto:
    git:
      url: https://github.com/MyLittleSuite/pine_bricks.git
      path: pine_network_jto
  pine_network_request:
    git:
      url: https://github.com/MyLittleSuite/pine_bricks.git
      path: pine_network_request
  pine_network_response:
    git:
      url: https://github.com/MyLittleSuite/pine_bricks.git
      path: pine_network_response
  pine_page:
    git:
      url: https://github.com/MyLittleSuite/pine_bricks.git
      path: pine_page
  pine_repository:
    git:
      url: https://github.com/MyLittleSuite/pine_bricks.git
      path: pine_repository
  pine_retrofit:
    git:
      url: https://github.com/MyLittleSuite/pine_bricks.git
      path: pine_retrofit
  pine_service:
    git:
      url: https://github.com/MyLittleSuite/pine_bricks.git
      path: pine_service
```

After running mason get you'll face random errors as I mentioned above
