### ISSUE TITLE
feat: partial file as input variable

### ISSUE THREAD

**Issue by josh-burton** [felangel/mason#728]
**Description**

This may already be possible but I can't figure out how.

Is it possible to pass a partial file as an input variable?

**Requirements**

**Additional Context**

**Comment by felangel** [comment]
Hi @josh-burton 👋
Thanks for opening an issue!

Can you please provide a bit more context regarding what you’re trying to achieve? I’m not sure I fully understand your question. Thanks! 🙏

**Comment by felangel** [comment]
@josh-burton so in your case you want the template consumer to specify a local path to the files (on their own machine) and the brick would insert the contents of these files into the corresponding slots in the generated pubspec.yaml?

**Comment by josh-burton** [comment]
> @josh-burton so in your case you want the template consumer to specify a local path to the files (on their own machine) and the brick would insert the contents of these files into the corresponding slots in the generated pubspec.yaml?

Yep thats right.

**Comment by felangel** [comment]
In that case, partials aren’t the right solution. I can create an example of how you can achieve this shortly (I’m away from a computer atm).

**Comment by josh-burton** [comment]
> 

Ok sure that would be great.

**Comment by felangel** [comment]
@josh-burton you can do something like:

**`brick.yaml`**

```yaml
name: example
description: A new brick created with the Mason CLI.

version: 0.1.0+1

environment:
  mason: ">=0.1.0-dev.41 <0.1.0"

vars:
  assets_path:
    type: string
    description: The path to the pubspec_assets.yaml file.
    default: ./pubspec_assets.yaml
    prompt: What is the assets path?
  fonts_path:
    type: string
    description: The path to the pubspec_fonts.yaml file.
    default: ./pubspec_fonts.yaml
    prompt: What is the fonts path?
```

**`__brick__/pubspec.yaml`**

```yaml
name: {{package}}

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
  {{{ pubspec_assets }}}
  {{{ pubspec_fonts }}}
```

`hooks/pre_gen.dart`

```dart
import 'dart:io';

import 'package:mason/mason.dart';

Future<void> run(HookContext context) async {
  final assetsFile = File(context.vars['assets_path']);
  final fontsFile = File(context.vars['fontsPath']);
  context.vars = {
    ...context.vars,
    'pubspec_assets`: assetsFile.readAsStringSync(),
    'pubspec_fonts`: fontsFile.readAsStringSync(),
  };
}
```

Hope that helps 👍
