### ISSUE TITLE
fix: OS Error: The system cannot find the path specified ( When brick installed globally )

### ISSUE THREAD

**Issue by amebrahimi** [felangel/mason#75]
**Description**
When I install a brick globally from GitHub and try to use it I get this error.
```CMD
FileSystemException: Directory listing failed, path = 'C:\Users\user\AppData\Local\Mason\Cache\git\useful_bricks_83a860a417bba07e93659860bfb3e3e93cb1b5b204e555e8fcca581839f895bb\bricks\freezed\__brick__\*' (OS Error: The system cannot find the path specified.
, errno = 3)
```
Os: Windows-10

**Steps To Reproduce**

1. Push a brick to GitHub
2. Install the brick globally from GitHub
4. Try to run `mason make brick_name`

**Comment by amebrahimi** [comment]
I apologize for creating this issue. I've changed my mason.yaml file from:
```yaml
bricks:
  freezed:
    path: bricks/freezed
```
to: 
```yaml
bricks:
  freezed:
    path: bricks\freezed
```
And the issue got fixed
