### ISSUE TITLE
feat: Output path

### ISSUE THREAD

**Issue by passsy** [felangel/mason#76]
**Description**

`mason make` creates the output in `cwd`. I'd prefer when I can specify an output dir.

`mason make --out some/path`

Additionally, the name of the output folder should be adjustable in `brick.yaml`.

```yaml
name: mytemplate
description: Template specifying an output path
dir_name: {{id}}_{{name}} # <-- using vars
vars:
  - id
  - name
```

So that `mason make mytemplate --id 3 --name hello --out projects` generates

`./projects/3_hello/<__brick__-files>`
