### ISSUE TITLE
feat: Limiting var values

### ISSUE THREAD

**Issue by OldMetalmind** [felangel/mason#849]
**Description**

Have a way to limit the responses of values for the variable. 

**Requirements**

- [ ] Include new parameter to vars called `values`.
- [ ] Fail if user inputs a value not included in the limited answer. 

**Additional Context**

I might want to restrict the values set in a variable defined in the `brick.yaml` to be one of the values of an array. 
Example:

```yaml
vars:
  name:
    type: string
    values: ['Max', 'Charlie', 'Cooper']  # The possible answers.
    description: Pick one of the valid names for your dog
    default: Max
    prompt: What is the name of your dog? #  Show the default value and possible values grey out.
```
